export const metaData = {
  "/": {
    slug: "/",
    title: "Software Engineering | U Tech",
    description:
      "We provide expert software engineering, IoT Product Development and IT Consultancy services.",
    keywords: ["software", "IoT", "product engineering", "consultancy"],
    image: "https://usystem.software/small-logo.png",
    url: "https://usystem.software",
    category: "Homepage",
    published: "August 2025",
  },
  contact: {
    slug: "contact",
    title: "Contact Us | U Tech",
    description: "Get in touch with our team for inquiries and support.",
    keywords: ["contact", "support", "help", "U Tech"],
    image: "https://usystem.software/banner/contact-us.jpg",
    url: "https://usystem.software/contact",
    category: "Contact",
    published: "August 2025",
  },

  bookcall: {
    slug: "bookcall",
    title: "Book a Call | U Tech",
    description: "Schedule a consultation with our experts.",
    keywords: ["book call", "consultation", "meeting", "U Tech"],
    image: "https://usystem.software/banner/bookcall-banner.jpg",
    url: "https://usystem.software/bookcall",
    category: "Contact",
    published: "August 2025",
  },
  agriculture: {
    slug: "agriculture",
    title: "Agriculture Industry Solutions | U Tech",
    description: "Discover U Tech's innovative digital and technology solutions for the agriculture industry. Empowering farmers, agribusinesses, and supply chains with smart, sustainable, and data-driven tools.",
    keywords: [
      "agriculture technology",
      "agritech solutions",
      "farming innovation",
      "U Tech agriculture",
      "smart farming",
      "agriculture industry solutions"
    ],
    image: "https://usystem.software/banner/agriculture-banner.jpg",
    url: "https://usystem.software/industries/agriculture",
    category: "Industries",
    published: "August 2025",
  },
  aviation: {
    slug: "aviation",
    title: "Aviation Industry Solutions | U Tech",
    description: "Explore our innovative solutions for the aviation industry.",
    keywords: ["aviation", "industry solutions", "U Tech"],
    image: "https://usystem.software/banner/aviation-banner.jpg",
    url: "https://usystem.software/industries/aviation",
    category: "Industries",
    published: "August 2025",
  },
  banking: {
    slug: "banking",
    title: "Banking Industry Solutions | U Tech",
    description: "Discover our tailored solutions for the banking sector.",
    keywords: ["banking", "industry solutions", "U Tech"],
    image: "https://usystem.software/banner/new-banking-banner.jpg",
    url: "https://usystem.software/industries/banking",
    category: "Industries",
    published: "August 2025",
  },
  construction: {
    slug: "construction",
    title: "Construction Industry Solutions | U Tech",
    description: "Innovative solutions for the construction industry.",
    keywords: ["construction", "industry solutions", "U Tech"],
    image: "https://usystem.software/banner/aec-banner.jpg",
    url: "https://usystem.software/industries/construction",
    category: "Industries",
    published: "August 2025",
  },
  corrections: {
    slug: "corrections",
    title: "Corrections Industry Solutions | U Tech",
    description: "Solutions tailored for the corrections industry.",
    keywords: ["corrections", "industry solutions", "U Tech"],
    image: "https://usystem.software/banner/correction-banner.jpg",
    url: "https://usystem.software/industries/corrections",
    category: "Industries",
    published: "August 2025",
  },
  "e-learning-education": {
    slug: "e-learning-education",
    title: "E-Learning & Education Solutions | U Tech",
    description: "Transformative solutions for e-learning and education.",
    keywords: ["e-learning", "education", "industry solutions", "U Tech"],
    image: "https://usystem.software/banner/e-learning-banner.jpg",
    url: "https://usystem.software/industries/e-learning-education",
    category: "Industries",
    published: "August 2025",
  },
  "energy-utilities": {
    slug: "energy-utilities",
    title: "Energy & Utilities Industry Solutions | U Tech",
    description: "Innovative solutions for energy and utilities.",
    keywords: ["energy", "utilities", "industry solutions", "U Tech"],
    image: "https://usystem.software/banner/utilities-banner.jpg",
    url: "https://usystem.software/industries/energy-utilities",
    category: "Industries",
    published: "August 2025",
  },
  "environmental-management": {
    slug: "environmental-management",
    title: "Environmental Management Solutions | U Tech",
    description: "Solutions for effective environmental management.",
    keywords: ["environmental management", "industry solutions", "U Tech"],
    image: "https://usystem.software/banner/env-mang-banner.jpg",
    url: "https://usystem.software/industries/environmental-management",
    category: "Industries",
    published: "August 2025",
  },
  finance: {
    slug: "finance",
    title: "Finance Industry Solutions | U Tech",
    description: "Comprehensive solutions for the finance industry.",
    keywords: ["finance", "industry solutions", "U Tech"],
    image: "https://usystem.software/banner/finance-banner.jpg",
    url: "https://usystem.software/industries/finance",
    category: "Industries",
    published: "August 2025",
  },
  "food-beverage": {
    slug: "food-beverage",
    title: "Food & Beverage Industry Solutions | U Tech",
    description: "Innovative solutions for the food and beverage sector.",
    keywords: ["food", "beverage", "industry solutions", "U Tech"],
    image: "https://usystem.software/banner/food-and-beverage-banner.jpg",
    url: "https://usystem.software/industries/food-beverage",
    category: "Industries",
    published: "August 2025",
  },
  gaming: {
    slug: "gaming",
    title: "Gaming Industry Solutions | U Tech",
    description: "Cutting-edge solutions for the gaming industry.",
    keywords: ["gaming", "industry solutions", "U Tech"],
    image:
      "https://usystem.software/banner/blockchain-social-media-platform-banner.jpg",
    url: "https://usystem.software/industries/gaming",
    category: "Industries",
    published: "August 2025",
  },
  healthcare: {
    slug: "healthcare",
    title: "Healthcare Industry Solutions | U Tech",
    description: "Innovative solutions for the healthcare sector.",
    keywords: ["healthcare", "industry solutions", "U Tech"],
    image: "https://usystem.software/banner/healthcare-banner.jpg",
    url: "https://usystem.software/industries/healthcare",
    category: "Industries",
    published: "August 2025",
  },
  "hospitality-travel": {
    slug: "hospitality-travel",
    title: "Hospitality & Travel Industry Solutions | U Tech",
    description: "Solutions for the hospitality and travel industry.",
    keywords: ["hospitality", "travel", "industry solutions", "U Tech"],
    image: "https://usystem.software/banner/hospitality-banner2.jpg",
    url: "https://usystem.software/industries/hospitality-travel",
    category: "Industries",
    published: "August 2025",
  },
  hcm: {
    slug: "hcm",
    title: "Human Capital Management Solutions | U Tech",
    description: "Solutions for effective human capital management.",
    keywords: [
      "HCM",
      "human capital management",
      "industry solutions",
      "U Tech",
    ],
    image: "https://usystem.software/banner/hcm-banner.jpg",
    url: "https://usystem.software/industries/hcm",
    category: "Industries",
    published: "August 2025",
  },
  legal: {
    slug: "legal",
    title: "Legal Industry Solutions | U Tech",
    description: "Comprehensive solutions for the legal sector.",
    keywords: ["legal", "industry solutions", "U Tech"],
    image: "https://usystem.software/banner/legel-banner.jpg",
    url: "https://usystem.software/industries/legal",
    category: "Industries",
    published: "August 2025",
  },
  "media-entertainment": {
    slug: "media-entertainment",
    title: "Media & Entertainment Industry Solutions | U Tech",
    description: "Innovative solutions for media and entertainment.",
    keywords: ["media", "entertainment", "industry solutions", "U Tech"],
    image: "https://usystem.software/banner/media-enterntainment-banner.jpg",
    url: "https://usystem.software/industries/media-entertainment",
    category: "Industries",
    published: "August 2025",
  },
  "meetings-events": {
    slug: "meetings-events",
    title: "Meetings & Events Industry Solutions | U Tech",
    description: "Solutions for managing meetings and events effectively.",
    keywords: ["meetings", "events", "industry solutions", "U Tech"],
    image: "https://usystem.software/banner/meetings-events-banner.jpg",
    url: "https://usystem.software/industries/meetings-events",
    category: "Industries",
    published: "August 2025",
  },
  payments: {
    slug: "payments",
    title: "Payments Industry Solutions | U Tech",
    description: "Innovative solutions for payment processing.",
    keywords: ["payments", "industry solutions", "U Tech"],
    image: "https://usystem.software/banner/payment-banner.jpg",
    url: "https://usystem.software/industries/payments",
    category: "Industries",
    published: "August 2025",
  },
  "political-campaigns": {
    slug: "political-campaigns",
    title: "Political Campaigns Industry Solutions | U Tech",
    description: "Solutions for effective political campaign management.",
    keywords: ["political campaigns", "industry solutions", "U Tech"],
    image: "https://usystem.software/banner/political-campaigns-banner.jpg",
    url: "https://usystem.software/industries/political-campaigns",
    category: "Industries",
    published: "August 2025",
  },
  "real-estate": {
    slug: "real-estate",
    title: "Real Estate Industry Solutions | U Tech",
    description: "Innovative solutions for the real estate sector.",
    keywords: ["real estate", "industry solutions", "U Tech"],
    image: "https://usystem.software/banner/real-banner.jpg",
    url: "https://usystem.software/industries/real-estate",
    category: "Industries",
    published: "August 2025",
  },
  retail: {
    slug: "retail",
    title: "Retail Industry Solutions | U Tech",
    description: "Comprehensive solutions for the retail industry.",
    keywords: ["retail", "industry solutions", "U Tech"],
    image: "https://usystem.software/banner/retail-banner.jpg",
    url: "https://usystem.software/industries/retail",
    category: "Industries",
    published: "August 2025",
  },
  sports: {
    slug: "sports",
    title: "Sports Industry Solutions | U Tech",
    description: "Innovative solutions for the sports industry.",
    keywords: ["sports", "industry solutions", "U Tech"],
    image: "https://usystem.software/banner/sport-banner.jpg",
    url: "https://usystem.software/industries/sports",
    category: "Industries",
    published: "August 2025",
  },
  "supply-chain": {
    slug: "supply-chain",
    title: "Supply Chain Industry Solutions | U Tech",
    description: "Solutions for effective supply chain management.",
    keywords: ["supply chain", "industry solutions", "U Tech"],
    image: "https://usystem.software/banner/supply-chain-management-banner.jpg",
    url: "https://usystem.software/industries/supply-chain",
    category: "Industries",
    published: "August 2025",
  },
  telecommunications: {
    slug: "telecommunications",
    title: "Telecommunications Industry Solutions | U Tech",
    description: "Innovative solutions for the telecommunications sector.",
    keywords: ["telecommunications", "industry solutions", "U Tech"],
    image: "https://usystem.software/banner/telecom-hero-banner.jpg",
    url: "https://usystem.software/industries/telecommunications",
    category: "Industries",
    published: "August 2025",
  },

  "api-development": {
    slug: "api-development",
    title: "API Development Services | U Tech",
    description:
      "Get top-notch API development services to enhance your applications.",
    keywords: ["API development", "services", "U Tech"],
    image: "https://usystem.software/banner/api-development-banner.jpg",
    url: "https://usystem.software/services/api-development",
    category: "Services",
    published: "August 2025",
  },
  "application-development": {
    slug: "application-development",
    title: "Application Development Services | U Tech",
    description:
      "Custom application development services to meet your business needs.",
    keywords: ["application development", "services", "U Tech"],
    image: "https://usystem.software/banner/application-development-banner.jpg",
    url: "https://usystem.software/services/application-development",
    category: "Services",
    published: "August 2025",
  },
  "application-maintenance": {
    slug: "application-maintenance",
    title: "Application Maintenance Services | U Tech",
    description:
      "Reliable application maintenance services to keep your software running smoothly.",
    keywords: ["application maintenance", "services", "U Tech"],
    image: "https://usystem.software/banner/app-maintanance-banner.jpg",
    url: "https://usystem.software/services/application-maintenance",
    category: "Services",
    published: "August 2025",
  },
  "backup-disaster-recovery": {
    slug: "backup-disaster-recovery",
    title: "Backup & Disaster Recovery Services | U Tech",
    description:
      "Comprehensive backup and disaster recovery services to protect your data.",
    keywords: ["backup", "disaster recovery", "services", "U Tech"],
    image: "https://usystem.software/banner/backup-recovery-banner.jpg",
    url: "https://usystem.software/services/backup-disaster-recovery",
    category: "Services",
    published: "August 2025",
  },
  bpo: {
    slug: "bpo",
    title: "Business Process Outsourcing Services | U Tech",
    description:
      "Streamline your operations with our business process outsourcing services.",
    keywords: ["BPO", "business process outsourcing", "services", "U Tech"],
    image:
      "https://usystem.software/banner/business-process-outsourcing-banner.jpg",
    url: "https://usystem.software/services/bpo",
    category: "Services",
    published: "August 2025",
  },
  "custom-software": {
    slug: "custom-software",
    title: "Custom Software Services | U Tech",
    description:
      "Tailored software solutions to meet your unique business requirements.",
    keywords: ["custom software", "services", "U Tech"],
    image: "https://usystem.software/banner/services.jpg",
    url: "https://usystem.software/services/custom-software",
    category: "Services",
    published: "August 2025",
  },
  "data-integration": {
    slug: "data-integration",
    title: "Data Integration Services | U Tech",
    description: "Seamless data integration services to unify your systems.",
    keywords: ["data integration", "services", "U Tech"],
    image: "https://usystem.software/banner/backup-recovery-banner.jpg",
    url: "https://usystem.software/services/data-integration",
    category: "Services",
    published: "August 2025",
  },
  "data-management": {
    slug: "data-management",
    title: "Data Management Services | U Tech",
    description:
      "Effective data management services to optimize your data usage.",
    keywords: ["data management", "services", "U Tech"],
    image: "https://usystem.software/banner/data-management-banner.jpg",
    url: "https://usystem.software/services/data-management",
    category: "Services",
    published: "August 2025",
  },
  devops: {
    slug: "devops",
    title: "DevOps Services | U Tech",
    description:
      "Enhance your development and operations with our DevOps services.",
    keywords: ["DevOps", "services", "U Tech"],
    image: "https://usystem.software/banner/hero-img-banner-devops.jpg",
    url: "https://usystem.software/services/devops",
    category: "Services",
    published: "August 2025",
  },
  "digital-transformation": {
    slug: "digital-transformation",
    title: "Digital Transformation Services | U Tech",
    description:
      "Transform your business with our digital transformation services.",
    keywords: ["digital transformation", "services", "U Tech"],
    image: "https://usystem.software/banner/digital-transformation-banner.jpg",
    url: "https://usystem.software/services/digital-transformation",
    category: "Services",
    published: "August 2025",
  },
  finops: {
    slug: "finops",
    title: "FinOps Services | U Tech",
    description: "Optimize your financial operations with our FinOps services.",
    keywords: ["FinOps", "financial operations", "services", "U Tech"],
    image: "https://usystem.software/banner/finops.jpg",
    url: "https://usystem.software/services/finops",
    category: "Services",
    published: "August 2025",
  },
  "implementation-deployment": {
    slug: "implementation-deployment",
    title: "Implementation & Deployment Services | U Tech",
    description:
      "Expert implementation and deployment services for your software.",
    keywords: ["implementation", "deployment", "services", "U Tech"],
    image: "https://usystem.software/banner/implementation.jpg",
    url: "https://usystem.software/services/implementation-deployment",
    category: "Services",
    published: "August 2025",
  },
  "infrastructure-support": {
    slug: "infrastructure-support",
    title: "Infrastructure Support Services | U Tech",
    description:
      "Reliable infrastructure support services to keep your systems running.",
    keywords: ["infrastructure support", "services", "U Tech"],
    image: "https://usystem.software/banner/infrastructuresupport.jpg",
    url: "https://usystem.software/services/infrastructure-support",
    category: "Services",
    published: "August 2025",
  },
  "migrations-upgrades": {
    slug: "migrations-upgrades",
    title: "Migrations & Upgrades Services | U Tech",
    description: "Seamless migrations and upgrades for your software systems.",
    keywords: ["migrations", "upgrades", "services", "U Tech"],
    image: "https://usystem.software/banner/MigrationsUpgrades.jpg",
    url: "https://usystem.software/services/migrations-upgrades",
    category: "Services",
    published: "August 2025",
  },
  noc: {
    slug: "noc",
    title: "NOC Services | U Tech",
    description: "24/7 Network Operations Center services for your business.",
    keywords: ["NOC", "network operations center", "services", "U Tech"],
    image: "https://usystem.software/banner/noc.jpg",
    url: "https://usystem.software/services/noc",
    category: "Services",
    published: "August 2025",
  },
  "partner-support": {
    slug: "partner-support",
    title: "Partner Product Support Services | U Tech",
    description: "Comprehensive support for partner products.",
    keywords: ["partner product support", "services", "U Tech"],
    image: "https://usystem.software/banner/partner.jpg",
    url: "https://usystem.software/services/partner-support",
    category: "Services",
    published: "August 2025",
  },
  plm: {
    slug: "plm",
    title: "Product Lifecycle Management (PLM) Services | U Tech",
    description:
      "Manage your product lifecycle effectively with our PLM services.",
    keywords: ["PLM", "product lifecycle management", "services", "U Tech"],
    image: "https://usystem.software/banner/product-lifecycle-management.jpeg",
    url: "https://usystem.software/services/plm",
    category: "Services",
    published: "August 2025",
  },
  "qa-testing": {
    slug: "qa-testing",
    title: "QA Testing Services | U Tech",
    description: "Ensure quality with our comprehensive QA testing services.",
    keywords: ["QA testing", "quality assurance", "services", "U Tech"],
    image: "https://usystem.software/banner/quality-assurance-banner.jpg",
    url: "https://usystem.software/services/qa-testing",
    category: "Services",
    published: "August 2025",
  },
  "sla-support": {
    slug: "sla-support",
    title: "SLA Support Services | U Tech",
    description: "Reliable SLA support services to meet your business needs.",
    keywords: ["SLA support", "services", "U Tech"],
    image: "https://usystem.software/banner/sla-support.jpeg",
    url: "https://usystem.software/services/sla-support",
    category: "Services",
    published: "August 2025",
  },
  "software-security": {
    slug: "software-security",
    title: "Software Security Services | U Tech",
    description:
      "Protect your software with our comprehensive security services.",
    keywords: ["software security", "services", "U Tech"],
    image: "https://usystem.software/banner/software-security.jpeg",
    url: "https://usystem.software/services/software-security",
    category: "Services",
    published: "August 2025",
  },
  "startup-mvp": {
    slug: "startup-mvp",
    title: "Startup & MVP Services | U Tech",
    description: "Launch your startup with our MVP development services.",
    keywords: ["startup", "MVP", "services", "U Tech"],
    image: "https://usystem.software/banner/startup-mvp.jpeg",
    url: "https://usystem.software/services/startup-mvp",
    category: "Services",
    published: "August 2025",
  },
  "systems-integration": {
    slug: "systems-integration",
    title: "Systems Integration Services | U Tech",
    description: "Seamless systems integration services for your business.",
    keywords: ["systems integration", "services", "U Tech"],
    image: "https://usystem.software/banner/systems-integration.jpeg",
    url: "https://usystem.software/services/systems-integration",
    category: "Services",
    published: "August 2025",
  },
  "animation-graphic-design": {
    slug: "animation-graphic-design",
    title: "Animation & Graphic Design Solutions | U Tech",
    description:
      "Creative animation and graphic design solutions for your projects.",
    keywords: ["animation", "graphic design", "solutions", "U Tech"],
    image: "https://usystem.software/banner/animation-graphic-design-banner.jpg",
    url: "https://usystem.software/solutions/animation-graphic-design",
    category: "Solutions",
    published: "August 2025",
  },
  "artificial-intelligence": {
    slug: "ai",
    title: "Artificial Intelligence Solutions | U Tech",
    description: "Leverage AI solutions to transform your business operations.",
    keywords: ["artificial intelligence", "solutions", "U Tech"],
    image: "https://usystem.software/banner/ai.jpg",
    url: "https://usystem.software/solutions/ai",
    category: "Solutions",
    published: "August 2025",
  },
  "asset-tracking": {
    slug: "asset-tracking",
    title: "Asset Tracking Solutions | U Tech",
    description:
      "Innovative asset tracking solutions to manage your resources effectively.",
    keywords: ["asset tracking", "solutions", "U Tech"],
    image: "https://usystem.software/banner/asset-tracking.jpg",
    url: "https://usystem.software/solutions/asset-tracking",
    category: "Solutions",
    published: "August 2025",
  },
  "ar-vr": {
    slug: "ar-vr",
    title: "AR / VR Solutions | U Tech",
    description: "Cutting-edge AR and VR solutions for immersive experiences.",
    keywords: ["AR", "VR", "solutions", "U Tech"],
    image: "https://usystem.software/banner/ar-vr.jpg",
    url: "https://usystem.software/solutions/ar-vr",
    category: "Solutions",
    published: "August 2025",
  },
  aws: {
    slug: "aws",
    title: "AWS Solutions | U Tech",
    description:
      "Comprehensive AWS solutions to enhance your cloud infrastructure.",
    keywords: ["AWS", "cloud solutions", "U Tech"],
    image: "https://usystem.software/banner/aws.jpg",
    url: "https://usystem.software/solutions/aws",
    category: "Solutions",
    published: "August 2025",
  },
  autodesk: {
    slug: "autodesk",
    title: "Autodesk Solutions | U Tech",
    description: "Expert Autodesk solutions for design and engineering.",
    keywords: ["Autodesk", "design solutions", "U Tech"],
    image: "https://usystem.software/banner/autodesk.jpg",
    url: "https://usystem.software/solutions/autodesk",
    category: "Solutions",
    published: "August 2025",
  },
  biometrics: {
    slug: "biometrics",
    title: "Biometrics Solutions | U Tech",
    description: "Advanced biometrics solutions for secure identification.",
    keywords: ["biometrics", "security solutions", "U Tech"],
    image: "https://usystem.software/banner/biometrics.jpg",
    url: "https://usystem.software/solutions/biometrics",
    category: "Solutions",
    published: "August 2025",
  },
  blockchain: {
    slug: "blockchain",
    title: "Blockchain Solutions | U Tech",
    description: "Innovative blockchain solutions for secure transactions.",
    keywords: ["blockchain", "solutions", "U Tech"],
    image: "https://usystem.software/banner/blockchain.jpg",
    url: "https://usystem.software/solutions/blockchain",
    category: "Solutions",
    published: "August 2025",
  },
  "bi-analytics": {
    slug: "bi-analytics",
    title: "Business Intelligence Solutions | U Tech",
    description:
      "Transform your data into actionable insights with our BI solutions.",
    keywords: ["business intelligence", "BI", "solutions", "U Tech"],
    image: "https://usystem.software/banner/bi-analytics.jpg",
    url: "https://usystem.software/solutions/bi-analytics",
    category: "Solutions",
    published: "August 2025",
  },
  cms: {
    slug: "cms",
    title: "CMS Solutions | U Tech",
    description: "Robust CMS solutions for effective content management.",
    keywords: ["CMS", "content management", "solutions", "U Tech"],
    image: "https://usystem.software/banner/cms-banner.jpeg",
    url: "https://usystem.software/solutions/cms",
    category: "Solutions",
    published: "August 2025",
  },
  crm: {
    slug: "crm",
    title: "CRM Solutions | U Tech",
    description: "Enhance customer relationships with our CRM solutions.",
    keywords: [
      "CRM",
      "customer relationship management",
      "solutions",
      "U Tech",
    ],
    image:
      "https://usystem.software/banner/crm-development-services-banner.jpg",
    url: "https://usystem.software/solutions/crm",
    category: "Solutions",
    published: "August 2025",
  },
  cloud: {
    slug: "cloud",
    title: "Cloud Solutions | U Tech",
    description: "Scalable cloud solutions to meet your business needs.",
    keywords: ["cloud", "solutions", "U Tech"],
    image: "https://usystem.software/banner/cloud-application-development.jpg",
    url: "https://usystem.software/solutions/cloud",
    category: "Solutions",
    published: "August 2025",
  },
  database: {
    slug: "database",
    title: "Database Solutions | U Tech",
    description: "Efficient database solutions for data management.",
    keywords: ["database", "solutions", "U Tech"],
    image: "https://usystem.software/banner/custom-database-development-services-banner.jpg",
    url: "https://usystem.software/solutions/database",
    category: "Solutions",
    published: "August 2025",
  },
  "digital-asset-management": {
    slug: "digital-asset-management",
    title: "Digital Asset Management Solutions | U Tech",
    description:
      "Manage your digital assets effectively with our DAM solutions.",
    keywords: ["digital asset management", "DAM", "solutions", "U Tech"],
    image: "https://usystem.software/banner/digital-asset-management-banner.jpg",
    url: "https://usystem.software/solutions/digital-asset-management",
    category: "Solutions",
    published: "August 2025",
  },
  "digital-marketing": {
    slug: "digital-marketing",
    title: "Digital Marketing Solutions | U Tech",
    description:
      "Boost your online presence with our digital marketing solutions.",
    keywords: ["digital marketing", "solutions", "U Tech"],
    image: "https://usystem.software/banner/digital-marketing-banner.jpg",
    url: "https://usystem.software/solutions/digital-marketing",
    category: "Solutions",
    published: "August 2025",
  },
  "document-management": {
    slug: "document-management",
    title: "Document Management Solutions | U Tech",
    description: "Streamline your document management with our solutions.",
    keywords: ["document management", "solutions", "U Tech"],
    image: "https://usystem.software/banner/document-management-banner.jpg",
    url: "https://usystem.software/solutions/document-management",
    category: "Solutions",
    published: "August 2025",
  },
  "embedded-software": {
    slug: "embedded-software",
    title: "Embedded Software Solutions | U Tech",
    description: "Custom embedded software solutions for your devices.",
    keywords: ["embedded software", "solutions", "U Tech"],
    image: "https://usystem.software/banner/embedded-software-banner.jpg",
    url: "https://usystem.software/solutions/embedded-software",
    category: "Solutions",
    published: "August 2025",
  },
  erp: {
    slug: "erp",
    title: "ERP Solutions | U Tech",
    description:
      "Comprehensive ERP solutions to streamline your business processes.",
    keywords: ["ERP", "enterprise resource planning", "solutions", "U Tech"],
    image: "https://usystem.software/banner/erp-banner.jpg",
    url: "https://usystem.software/solutions/erp",
    category: "Solutions",
    published: "August 2025",
  },
  "facilities-management": {
    slug: "facilities-management",
    title: "Facilities Management Solutions | U Tech",
    description: "Optimize your facilities management with our solutions.",
    keywords: ["facilities management", "solutions", "U Tech"],
    image: "https://usystem.software/banner/facility-management-banner.jpg",
    url: "https://usystem.software/solutions/facilities-management",
    category: "Solutions",
    published: "August 2025",
  },
  "fraud-protection": {
    slug: "fraud-protection",
    title: "Fraud Protection Solutions | U Tech",
    description: "Protect your business with our fraud protection solutions.",
    keywords: ["fraud protection", "solutions", "U Tech"],
    image: "https://usystem.software/banner/fraud-protection-banner.jpg",
    url: "https://usystem.software/solutions/fraud-protection",
    category: "Solutions",
    published: "August 2025",
  },
  gis: {
    slug: "gis",
    title: "GIS Solutions | U Tech",
    description:
      "Geographic Information System solutions for better decision-making.",
    keywords: ["GIS", "geographic information system", "solutions", "U Tech"],
    image: "https://usystem.software/banner/gis-banner.jpg",
    url: "https://usystem.software/solutions/gis",
    category: "Solutions",
    published: "August 2025",
  },
  "google-cloud": {
    slug: "google-cloud",
    title: "Google Cloud Solutions | U Tech",
    description: "Leverage Google Cloud solutions for your business needs.",
    keywords: ["Google Cloud", "cloud solutions", "U Tech"],
    image: "https://usystem.software/banner/google-cloud-banner.jpg",
    url: "https://usystem.software/solutions/google-cloud",
    category: "Solutions",
    published: "August 2025",
  },
  ibm: {
    slug: "ibm",
    title: "IBM Solutions | U Tech",
    description: "Expert IBM solutions for enterprise applications.",
    keywords: ["IBM", "enterprise solutions", "U Tech"],
    image: "https://usystem.software/banner/ibm-new-banner.jpg",
    url: "https://usystem.software/solutions/ibm",
    category: "Solutions",
    published: "August 2025",
  },
  iot: {
    slug: "iot",
    title: "IOT & M2M Solutions | U Tech",
    description: "Innovative IoT and M2M solutions for connected devices.",
    keywords: ["IoT", "M2M", "solutions", "U Tech"],
    image: "https://usystem.software/banner/iot-m2m-banner.jpg",
    url: "https://usystem.software/solutions/iot",
    category: "Solutions",
    published: "August 2025",
  },
  kiosk: {
    slug: "kiosk",
    title: "Kiosk Solutions | U Tech",
    description: "Custom kiosk solutions for various applications.",
    keywords: ["kiosk", "solutions", "U Tech"],
    image: "https://usystem.software/banner/kiosk-banner.jpg",
    url: "https://usystem.software/solutions/kiosk",
    category: "Solutions",
    published: "August 2025",
  },
  "ui-ux": {
    slug: "ui-ux",
    title: "Layout / UI / UX Solutions | U Tech",
    description: "Enhance user experience with our UI/UX design solutions.",
    keywords: ["UI", "UX", "design solutions", "U Tech"],
    image: "https://usystem.software/banner/ui-ux-banner.jpg",
    url: "https://usystem.software/solutions/ui-ux",
    category: "Solutions",
    published: "August 2025",
  },
  microsoft: {
    slug: "microsoft",
    title: "Microsoft Solutions | U Tech",
    description: "Comprehensive Microsoft solutions for your business.",
    keywords: ["Microsoft", "solutions", "U Tech"],
    image: "https://usystem.software/banner/microsoft.jpg",
    url: "https://usystem.software/solutions/microsoft",
    category: "Solutions",
    published: "August 2025",
  },
  netsuite: {
    slug: "netsuite",
    title: "NetSuite Solutions | U Tech",
    description: "Optimize your business processes with NetSuite solutions.",
    keywords: ["NetSuite", "solutions", "U Tech"],
    image: "https://usystem.software/banner/netsuite.jpg",
    url: "https://usystem.software/solutions/netsuite",
    category: "Solutions",
    published: "August 2025",
  },
  oracle: {
    slug: "oracle",
    title: "Oracle Solutions | U Tech",
    description: "Expert Oracle solutions for enterprise applications.",
    keywords: ["Oracle", "enterprise solutions", "U Tech"],
    image: "https://usystem.software/banner/oracle-banner.jpg",
    url: "https://usystem.software/solutions/oracle",
    category: "Solutions",
    published: "August 2025",
  },
  salesforce: {
    slug: "salesforce",
    title: "Salesforce Solutions | U Tech",
    description:
      "Enhance customer relationship management with Salesforce solutions.",
    keywords: ["Salesforce", "CRM solutions", "U Tech"],
    image: "https://usystem.software/banner/salesforce-banner.jpg",
    url: "https://usystem.software/solutions/salesforce",
    category: "Solutions",
    published: "August 2025",
  },
  sap: {
    slug: "sap",
    title: "SAP Solutions | U Tech",
    description:
      "Comprehensive SAP solutions for enterprise resource planning.",
    keywords: ["SAP", "ERP solutions", "U Tech"],
    image: "https://usystem.software/banner/sap-banner.jpg",
    url: "https://usystem.software/solutions/sap",
    category: "Solutions",
    published: "August 2025",
  },
  uipath: {
    slug: "uipath",
    title: "UiPath Solutions | U Tech",
    description: "Automate your business processes with UiPath solutions.",
    keywords: ["UiPath", "automation solutions", "U Tech"],
    image: "https://usystem.software/banner/uipath-banner.jpg",
    url: "https://usystem.software/solutions/uipath",
    category: "Solutions",
    published: "August 2025",
  },
  ukg: {
    slug: "ukg",
    title: "UKG Solutions | U Tech",
    description: "Optimize your workforce management with UKG solutions.",
    keywords: ["UKG", "workforce management", "solutions", "U Tech"],
    image: "https://usystem.software/banner/custom-ukg-banner.jpg",
    url: "https://usystem.software/solutions/ukg",
    category: "Solutions",
    published: "August 2025",
  },
  "web-development": {
    slug: "web-development",
    title: "Web Development Solutions | U Tech",
    description:
      "Custom web development solutions to enhance your online presence.",
    keywords: ["web development", "solutions", "U Tech"],
    image: "https://usystem.software/banner/web-development-banner.jpg",
    url: "https://usystem.software/solutions/web-development",
    category: "Solutions",
    published: "August 2025",
  },
  "about-us": {
    slug: "about-us",
    title: "About Us | U Tech",
    description: "Learn more about U Tech, our mission, and our values.",
    keywords: ["about us", "U Tech", "company information"],
    image: "https://usystem.software/banner/about.webp",
    url: "https://usystem.software/company/about-us",
    category: "Company",
    published: "August 2025",
  },
  referral: {
    slug: "referral",
    title: "Employee Referral Program | Careers at U Tech",
    description:
      "Refer talented professionals to U Tech and earn exciting rewards! Join our referral program and help us build an innovative team.",
    keywords: [
      "employee referral program",
      "refer a friend jobs",
      "U Tech careers",
      "job referral rewards"
    ],
    image: "https://usystem.software/banner/referral-banner.jpeg",
    url: "https://usystem.software/company/careers/referral",
    category: "Company",
    published: "August 2025",
  },
  awards: {
    slug: "awards",
    title: "Awards | U Tech",
    description: "Discover the awards and recognitions received by U Tech.",
    keywords: ["awards", "recognitions", "U Tech"],
    image: "https://usystem.software/banner/awards-banner.jpg",
    url: "https://usystem.software/company/awards",
    category: "Company",
    published: "August 2025",
  },
  careers: {
    slug: "careers",
    title: "Careers at U Tech | Join Our Team",
    description: "Explore career opportunities and join the U Tech team.",
    keywords: ["careers", "jobs", "U Tech"],
    image: "https://usystem.software/banner/carrier-banner.jpeg",
    url: "https://usystem.software/company/careers",
    category: "Company",
    published: "August 2025",
  },
  events: {
    slug: "events",
    title: "Ganesh Festival 2025 With Opening the U Techology Website With VIP guests. Please accept the invitation and build the part of our happiness",
    description:
      "Celebrate the grand opening of Ganesh Festival 2025 at U Technology with joy, devotion, and cultural programs. Special VIP guests invited to mark this auspicious day.",
    keywords: [
      "Ganesh Festival 2025",
      "Ganpati Utsav U Tech",
      "Ganpati Festival 2025",
      "U Tech events",
      "Ganesh Festival VIP invite",
      "Hindu festival celebration"
    ],
    image: "https://usystem.software/assets/company/events/tumbnil.png",
    url: "https://usystem.software/company/events",
    category: "Festivals",
    published: "August 2025",
  },
  history: {
    slug: "history",
    title: "Company History | U Tech",
    description: "Learn about the history and milestones of U Tech.",
    keywords: ["history", "U Tech", "company milestones"],
    image: "https://usystem.software/banner/history-banner.jpg",
    url: "https://usystem.software/company/history",
    category: "Company",
    published: "August 2025",
  },
  locations: {
    slug: "locations",
    title: "Locations | U Tech",
    description: "Find out about U Tech's locations and offices worldwide.",
    keywords: ["locations", "U Tech", "company offices"],
    image: "https://usystem.software/banner/location-banner.jpeg",
    url: "https://usystem.software/company/locations",
    category: "Company",
    published: "August 2025",
  },
  newsroom: {
    slug: "newsroom",
    title: "Newsroom | U Tech",
    description: "Access the latest news and press releases from U Tech.",
    keywords: ["newsroom", "press releases", "U Tech"],
    image: "https://usystem.software/banner/newsroom-banner.jpg",
    url: "https://usystem.software/company/newsroom",
    category: "Company",
    published: "August 2025",
  },
  "partners-affiliations": {
    slug: "partners-affiliations",
    title: "Partners & Affiliations | U Tech",
    description: "Learn about U Tech's partners and affiliations.",
    keywords: ["partners", "affiliations", "U Tech"],
    image: "https://usystem.software/banner/affiliations-banner.jpeg",
    url: "https://usystem.software/affiliations",
    category: "Company",
    published: "August 2025",
  },
  "people-and-culture": {
    slug: "people-and-culture",
    title: "People and Culture at U Tech | Join Us",
    description: "Discover the people and culture that make U Tech unique.",
    keywords: ["people", "culture", "U Tech"],
    image: "https://usystem.software/banner/history-banner.jpg",
    url: "https://usystem.software/company/people-and-culture",
    category: "Company",
    published: "August 2025",
  },
  reviews: {
    slug: "reviews",
    title: "Reviews of U Tech | Customer Feedback",
    description: "Read reviews and feedback from our customers.",
    keywords: ["reviews", "customer feedback", "U Tech"],
    image: "https://usystem.software/banner/reviews-banner.jpg",
    url: "https://usystem.software/company/reviews",
    category: "Company",
    published: "August 2025",
  },
  "full-stack-developer": {
    slug: "full-stack-developer",
    title: "Full Stack Developer Careers | U Tech",
    description:
      "Join U Tech as a Full Stack Developer. Work on scalable applications with React, Node.js, APIs, and cloud platforms.",
    keywords: [
      "Full Stack Developer",
      "Software Engineer Jobs",
      "React Developer",
      "Node.js Careers",
      "U Tech Careers",
    ],
    image: "https://usystem.software/assets/company/careers/fullstack-devp.jpeg",
    url: "https://usystem.software/company/careers/full-stack-developer",
    category: "Careers",
    published: "August 2025",
  },
  "frontend-developer": {
    slug: "frontend-developer",
    title: "Front End Developer Careers | U Tech",
    description:
      "We are hiring Front-End Developers to design and build web applications. Work with React, modern frameworks, and cross-functional teams.",
    keywords: [
      "Front End Developer",
      "Frontend Jobs",
      "React Developer",
      "UI Developer Careers",
      "U Tech Careers",
    ],
    image: "https://usystem.software/assets/company/careers/frontend-devp.jpeg",
    url: "https://usystem.software/company/careers/frontend-developer",
    category: "Careers",
    published: "August 2025",
  },
  "backend-developer": {
    slug: "backend-developer",
    title: "Backend Developer Careers | U Tech",
    description:
      "Apply for Backend Developer roles at U Tech. Build server-side applications, APIs, and work with databases and cloud platforms.",
    keywords: [
      "Backend Developer",
      "Node.js Jobs",
      "API Developer",
      "Server-side Engineer",
      "U Tech Careers",
    ],
    image: "https://usystem.software/assets/company/careers/backend-devp.jpeg",
    url: "https://usystem.software/company/careers/backend-developer",
    category: "Careers",
    published: "August 2025",
  },
  "digital-marketing-executive": {
    slug: "digital-marketing-executive",
    title: "Digital Marketing Executive Careers | U Tech",
    description:
      "Kickstart your career as a Digital Marketing Executive at U Tech. Work on SEO, social media, and content strategy.",
    keywords: [
      "Digital Marketing Jobs",
      "Marketing Executive Careers",
      "SEO Specialist",
      "Social Media Marketing",
      "U Tech Careers",
    ],
    image:
      "https://usystem.software/assets/company/careers/digital-marketing.webp",
    url: "https://usystem.software/company/careers/digital-marketing-executive",
    category: "Careers",
    published: "August 2025",
  },
  "ui-ux-designer": {
    slug: "ui-ux-designer",
    title: "UI/UX Designer Careers | U Tech",
    description:
      "We are hiring UI/UX Designers skilled in Figma, design systems, 3D, and motion graphics. Create user-friendly designs at U Tech.",
    keywords: [
      "UI Designer Jobs",
      "UX Designer Careers",
      "Figma Designer",
      "Creative Designer Jobs",
      "U Tech Careers",
    ],
    image: "https://usystem.software/assets/company/careers/uiux-designer.png",
    url: "https://usystem.software/company/careers/ui-ux-designer",
    category: "Careers",
    published: "August 2025",
  },
  "embedded-developer": {
    slug: "embedded-developer",
    title: "Embedded Developer Careers | U Tech",
    description:
      "We are looking for Embedded Developers experienced in microcontrollers, C programming, and hardware integrations.",
    keywords: [
      "Embedded Developer Jobs",
      "C Programmer Careers",
      "IoT Developer",
      "Microcontroller Engineer",
      "U Tech Careers",
    ],
    image: "https://usystem.software/assets/company/careers/embeded-devp.jpeg",
    url: "https://usystem.software/company/careers/embedded-developer",
    category: "Careers",
    published: "August 2025",
  },
  "hardware-engineer": {
    slug: "hardware-engineer",
    title: "Hardware Engineer Careers | U Tech",
    description:
      "Join U Tech as a Hardware Engineer. Work on embedded hardware design, circuit testing, and IoT systems.",
    keywords: [
      "Hardware Engineer Jobs",
      "Electronics Engineer Careers",
      "IoT Hardware Developer",
      "Embedded Systems Engineer",
      "U Tech Careers",
    ],
    image: "https://usystem.software/assets/company/careers/hardware-engineer.jpeg",
    url: "https://usystem.software/company/careers/hardware-engineer",
    category: "Careers",
    published: "August 2025",
  },
};
