export const guests = [
    {
        name: "Dr. Dnyaneshwar Kamble",
        title: "Founder of-  Arban Nidhi Bank Ltd., Mitcone President, Minister of state",
        img: "/assets/company/events/dnyaneshwar-kamble.jpg",
    },
    {
        name: "Ms. Vaishali(Tai) Ghodekar",
        title: "Ex-Mayor of Pimpri Chinchwad Municipal Corporation. Being a Doc",
        img: "/assets/company/events/vaishali-tai.jpg",
    },
    {
        name: "Mr. Baba Kamble",
        title: "National President: Auto, Taxi, Bus, Truck, Transport Federation",
        img: "/assets/company/events/baba-kamble.jpg",
    },
];

export const galleryImages = [
    "/assets/company/events/8.jpg",
    "/assets/company/events/12.jpg",
    "/assets/company/events/13.jpg",
    "/assets/company/events/14.jpg",
    "/assets/company/events/15.jpg",
    "/assets/company/events/17.jpg",
    "/assets/company/events/18.jpg",
    "/assets/company/events/19.jpg",
    "/assets/company/events/20.jpg",
    "/assets/company/events/21.jpg",
    "/assets/company/events/22.jpg",
    "/assets/company/events/23.jpg",
    "/assets/company/events/24.jpg",
    "/assets/company/events/25.jpg",
    "/assets/company/events/26.jpg",
    "/assets/company/events/27.jpg",
    "/assets/company/events/28.jpg",
    "/assets/company/events/29.jpg",
    "/assets/company/events/30.jpg",
    "/assets/company/events/31.jpg",
    "/assets/company/events/32.jpg",
    "/assets/company/events/33.jpg",
    "/assets/company/events/34.jpg",
    "/assets/company/events/35.jpg",
    "/assets/company/events/36.jpg",
    "/assets/company/events/37.jpg",
    "/assets/company/events/38.jpg",
    "/assets/company/events/39.jpg",
    "/assets/company/events/40.jpg",
    "/assets/company/events/41.jpg",
    "/assets/company/events/42.jpg",
    "/assets/company/events/43.jpg",
    "/assets/company/events/1.jpg",
    "/assets/company/events/2.jpg",
    "/assets/company/events/3.jpg",
    "/assets/company/events/4.jpg",
    "/assets/company/events/9.jpg",
    "/assets/company/events/10.jpg",
    "/assets/company/events/11.jpg",
    "/assets/company/events/5.jpg",
    "/assets/company/events/6.jpg",
    "/assets/company/events/16.jpg",
];

export const highlights = [
    "Grand Ganesh Aarti & Pooja Ceremony",
    "Traditional Cultural Performances",
    "Delicious Maha Prasad Distribution",
    "VIP Guest Interactions",
    "Eco-friendly Ganpati Decoration",
    "Spiritual Bhajans & Kirtans",
];

export const schedule = [
    { time: "04:00 PM", event: "Welcome Ceremony" },
    { time: "04:30 PM", event: "VIP Guest Speech & Blessings" },
    { time: "05:00 PM", event: "Cultural Performances , Dance & Employee Speech" },
    { time: "06:00 PM", event: "Aarti & Maha Prasad Distribution" },
    { time: "07:00 PM", event: "Dinner & All" },
];