name: Deploy Frontend

on:
  push:
    branches:
      - main # Change if you use a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # 3️⃣ Install dependencies
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      # 4️⃣ Build frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      # 5️⃣ Deploy via SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # Remove old frontend build
            rm -rf /var/www/UTECH/frontend/dist/*
            mkdir -p /var/www/UTECH/frontend/dist

            # Copy new build
            cp -r ./frontend/dist/* /var/www/UTECH/frontend/dist/

            # Reload Nginx to serve updated frontend
            sudo systemctl reload nginx
